Homework3
made-mlops-2022/Somov_Alexey pull request #4
Opened 2022-12-08 20:47 UTC by Kirinari

TODO: add points

2022-12-25 15:09 UTC, nickdndev commented
надо добавить самооценку

2022-12-25 15:09 UTC, nickdndev requested changes
надо добавить самооценку

2022-12-28 18:00 UTC, Kirinari commented
> надо добавить самооценку

готово

2022-12-30 15:23 UTC, nickdndev commented
итог:34

2022-12-30 15:23 UTC, nickdndev approved these changes

2022-12-31 08:51 UTC, merged